apiVersion: v1
entries:
  cert-manager-certs:
  - apiVersion: v1
    appVersion: v1.0.3
    created: "2020-10-28T09:02:32.387768068-07:00"
    description: A Helm chart for cert-manager and certs
    digest: 013f1f52d0debc9e1a84280d6d7100766a1c0473f802e53cc54c0b1d26d43f97
    name: cert-manager-certs
    type: application
    urls:
    - cert-manager-certs-v1.0.3.tgz
    version: v1.0.3
  kam:
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2020-10-28T09:02:32.387982595-07:00"
    description: KaaS Access Manager
    digest: de2f94cc91f17eb2cfa3c5aecebc922a8ec0502aff2a84e8b5ad1cd85d342354
    name: kam
    urls:
    - kam-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-28T09:02:32.373190054-07:00"
